# Generated by Django 5.1 on 2025-08-01 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_log", "0006_email_extra_headers_email_reply_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="email_log.email",
                        verbose_name="email",
                    ),
                ),
                ("esp", models.CharField(verbose_name="ESP")),
                ("metadata", models.JSONField()),
                ("type", models.CharField()),
                ("timestamp", models.DateTimeField()),
                ("event_id", models.CharField()),
                ("reject_reason", models.CharField(null=True)),
                (
                    "mta_response",
                    models.CharField(null=True, verbose_name="MTA Response"),
                ),
                ("tags", models.JSONField()),
                ("user_agent", models.CharField(null=True)),
                ("click_url", models.CharField(null=True, verbose_name="Click URL")),
                ("raw", models.JSONField()),
            ],
            options={
                "ordering": ["email", "timestamp"],
            },
        ),
    ]
